### ISSUE TITLE
User Agent Client Hints Examples

### ISSUE THREAD

**Issue by sergerdn** [51Degrees/device-detection-examples-go#1]
Hi, there. Do you have any plan to get that work finished?

https://github.com/51Degrees/device-detection-examples-go/blob/03e3ecfc6e9a27c68e3fa3737786e5ebbb1e1e46/dd/uach_test.go

**Comment by jwrosewell** [comment]
As this issue is almost identical to the one in the [device-detection-go](https://github.com/51Degrees/device-detection-go/issues/1) repository I'm going to close this one and we can consolidate questions and updates there. 

If a specific issue for the UACH example is needed then we can re-open then this issue.
